name: Makefile CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: HW0
      run: cd HW0 && make && cd words && make
      
    - name: HW1
      run: cd hw1 && make
      
      
